import { Header } from "@/ela-components";
import styles from "./layout.module.sass"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Usuarios",
    description: "Generated by create next app",
};
  

export default function Layout(props:{  
    children: React.ReactNode
}) {
    return <>
        <Header/>
        <main className={styles.main}>
            {props.children}  
        </main>
    </>
    
}
