import type { Metadata } from "next";
import "./globals.scss";
import {QuicksandFont } from "./lib/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={QuicksandFont.className}> 
        {children}
      </body>
    </html>
  );
}
