import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderMobile from '@/components/header-mobile'
import SideNav from '@/components/SideNav'
import MarginWidthWrapper from '@/components/MarginWidhtWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-white${inter.className}`}>
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <MarginWidthWrapper>
              <HeaderMobile />
              {children}
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  )
}
